/**
 * `dotlyte generate-types` — Generate TypeScript types from .env file.
 *
 * Usage:
 *   dotlyte generate-types [--input <file>] [--output <file>]
 *
 * Reads a .env file and generates a TypeScript interface with inferred types.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { coerce } from "../../coercion.js";

export async function generateTypes(args: string[]): Promise<void> {
  const inputFile = getArg(args, "--input") ?? findEnvFile();
  const outputFile = getArg(args, "--output") ?? "src/env.d.ts";

  if (!inputFile) {
    throw new Error(
      "No .env file found. Specify one with --input .env.example",
    );
  }

  const inputPath = resolve(inputFile);
  if (!existsSync(inputPath)) {
    throw new Error(`File not found: ${inputPath}`);
  }

  console.log(`\n🔧 dotlyte generate-types\n`);
  console.log(`  Input:  ${inputFile}`);
  console.log(`  Output: ${outputFile}\n`);

  const content = readFileSync(inputPath, "utf-8");
  const entries = parseEnvFile(content);

  const lines: string[] = [
    "/**",
    " * Auto-generated by `dotlyte generate-types`.",
    ` * Source: ${inputFile}`,
    ` * Generated: ${new Date().toISOString()}`,
    " *",
    " * Do not edit manually. Re-run `npx dotlyte generate-types` to update.",
    " */",
    "",
    "export interface DotlyteEnv {",
  ];

  for (const { key, value, comment } of entries) {
    const tsType = inferTsType(value);
    if (comment) {
      lines.push(`  /** ${comment} */`);
    }
    lines.push(`  ${key}: ${tsType};`);
  }

  lines.push("}");
  lines.push("");
  lines.push("declare global {");
  lines.push("  namespace NodeJS {");
  lines.push("    interface ProcessEnv extends DotlyteEnv {}");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  const output = lines.join("\n");
  const outputPath = resolve(outputFile);
  writeFileSync(outputPath, output, "utf-8");

  console.log(`  ✅ Generated ${entries.length} type definitions\n`);
}

interface EnvEntry {
  key: string;
  value: string;
  comment?: string;
}

function parseEnvFile(content: string): EnvEntry[] {
  const entries: EnvEntry[] = [];
  let pendingComment: string | undefined;

  for (const line of content.split("\n")) {
    const trimmed = line.trim();

    if (trimmed.startsWith("#")) {
      pendingComment = trimmed.slice(1).trim();
      continue;
    }

    if (!trimmed) {
      pendingComment = undefined;
      continue;
    }

    const stripped = trimmed.startsWith("export ") ? trimmed.slice(7).trim() : trimmed;
    const eqIdx = stripped.indexOf("=");
    if (eqIdx > 0) {
      const key = stripped.slice(0, eqIdx).trim();
      let value = stripped.slice(eqIdx + 1).trim();
      if (value.length >= 2 && value[0] === value[value.length - 1] && (value[0] === '"' || value[0] === "'")) {
        value = value.slice(1, -1);
      }
      entries.push({ key, value, comment: pendingComment });
      pendingComment = undefined;
    }
  }

  return entries;
}

function inferTsType(value: string): string {
  const coerced = coerce(value);

  if (coerced === null) return "string | null";
  if (typeof coerced === "boolean") return "string"; // env vars are always strings at runtime
  if (typeof coerced === "number") return "string";
  if (Array.isArray(coerced)) return "string";

  // Check if it looks like a URL
  try {
    new URL(value);
    return "string";
  } catch {
    // Not a URL
  }

  return "string";
}

function findEnvFile(): string | null {
  const candidates = [".env.example", ".env.sample", ".env.template", ".env"];
  for (const c of candidates) {
    if (existsSync(resolve(c))) return c;
  }
  return null;
}

function getArg(args: string[], flag: string): string | undefined {
  const idx = args.indexOf(flag);
  return idx >= 0 && idx + 1 < args.length ? args[idx + 1] : undefined;
}
