"""``dotlyte generate-types`` — Generate Python TypedDict from .env."""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path

from dotlyte.coercion import coerce


def run_generate_types(
    *,
    input_file: str | None = None,
    output_file: str | None = None,
) -> None:
    """Read a .env file and generate a Python ``TypedDict`` with inferred types.

    Args:
        input_file: Path to the .env source file. Auto-detected if ``None``.
        output_file: Output .py file path. Defaults to ``src/env_types.py``.

    """
    input_path_str = input_file or _find_env_file()
    if input_path_str is None:
        print(
            "❌ No .env file found. Specify one with --input .env.example",
            file=sys.stderr,
        )
        sys.exit(1)

    input_path = Path(input_path_str).resolve()
    if not input_path.is_file():
        print(f"❌ File not found: {input_path_str}", file=sys.stderr)
        sys.exit(1)

    output_path_str = output_file or "src/env_types.py"

    print("\n🔧 dotlyte generate-types\n")
    print(f"  Input:  {input_path_str}")
    print(f"  Output: {output_path_str}\n")

    content = input_path.read_text(encoding="utf-8")
    entries = _parse_env_file(content)

    now = datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        '"""Auto-generated by ``dotlyte generate-types``.',
        "",
        f"Source: {input_path_str}",
        f"Generated: {now}",
        "",
        "Do not edit manually. Re-run ``dotlyte generate-types`` to update.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import TypedDict",
        "",
        "",
        "class DotlyteEnv(TypedDict, total=False):",
        '    """Typed environment variables."""',
        "",
    ]

    if not entries:
        lines.append("    pass")
    else:
        for key, value, comment in entries:
            py_type = _infer_py_type(value)
            if comment:
                lines.append(f"    # {comment}")
            lines.append(f"    {key}: {py_type}")

    lines.append("")

    output_path = Path(output_path_str).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"  ✅ Generated {len(entries)} type definitions\n")


# ──── Internal helpers ────


def _parse_env_file(content: str) -> list[tuple[str, str, str | None]]:
    """Parse .env content into ``(key, value, comment)`` tuples."""
    entries: list[tuple[str, str, str | None]] = []
    pending_comment: str | None = None

    for line in content.splitlines():
        trimmed = line.strip()

        if trimmed.startswith("#"):
            pending_comment = trimmed[1:].strip()
            continue

        if not trimmed:
            pending_comment = None
            continue

        stripped = trimmed[7:].strip() if trimmed.startswith("export ") else trimmed
        eq_idx = stripped.find("=")
        if eq_idx > 0:
            key = stripped[:eq_idx].strip()
            value = stripped[eq_idx + 1 :].strip()
            if (
                len(value) >= 2
                and value[0] == value[-1]
                and value[0] in ('"', "'")
            ):
                value = value[1:-1]
            entries.append((key, value, pending_comment))
            pending_comment = None

    return entries


def _infer_py_type(value: str) -> str:
    """Infer a Python type annotation string from a raw .env value."""
    coerced = coerce(value)
    if coerced is None:
        return "str | None"
    if isinstance(coerced, bool):
        return "str"
    if isinstance(coerced, int):
        return "str"
    if isinstance(coerced, float):
        return "str"
    if isinstance(coerced, list):
        return "str"
    return "str"


def _find_env_file() -> str | None:
    """Search for common .env file names."""
    candidates = [".env.example", ".env.sample", ".env.template", ".env"]
    for c in candidates:
        if Path(c).resolve().is_file():
            return c
    return None
